name: Adamnite

on:
  pull_request:
    branches:
      - stable
      - stable-merge-to

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # NOTE: Still doesn't work
      # - name: Build
      #   run: go build -v ./...

      - name: Test VM
        run: go test -v ./VM

      - name: Test RPC
        run: go test -v ./rpc
